### ISSUE TITLE
AppArmor activation error

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#2]
On a new Ubuntu 14.04 in a VM, it runs okay until:

```
TASK: [cis | 4.5 Activate AppArmor (enforce) (Scored)] ************************ 
failed: [192.168.1.13] => {"changed": false, "cmd": "aa-enforce /etc/apparmor.d/*", "delta": "0:00:01.333396", "end": "2015-05-02 16:02:57.457397", "failed": true, "failed_when_result": true, "rc": 1, "start": "2015-05-02 16:02:56.124001", "stdout_lines": ["Profile for /etc/apparmor.d/abstractions not found, skipping"], "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/sbin/aa-enforce", line 30, in <module>
    tool.cmd_enforce()
  File "/usr/lib/python3/dist-packages/apparmor/tools.py", line 153, in cmd_enforce
    apparmor.read_profiles()
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 2564, in read_profiles
    read_profile(profile_dir + '/' + file, True)
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 2590, in read_profile
    profile_data = parse_profile_data(data, file, 0)
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 2843, in parse_profile_data
    store_list_var(filelist[file]['lvar'], list_var, value, var_operation)
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 3274, in store_list_var
    raise AppArmorException(_('An existing variable redefined: %s') % list_var)
apparmor.common.AppArmorException: 'An existing variable redefined: @{MOZ_LIBDIR}'
stdout: Profile for /etc/apparmor.d/abstractions not found, skipping

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/paul/playbook.retry

192.168.1.13               : ok=43   changed=0    unreachable=0    failed=1  
```

**Comment by awailly** [comment]
Can you provide a link to the iso file used for the install ?

**Comment by awailly** [comment]
Seems to be a known bug https://bugs.launchpad.net/apparmor/+bug/1378095. I will try to bypass aa-enforce.
